version: '3.8'
services:
  backend:
    build: .
    command: sh -c "gunicorn --workers=4 --bind 0.0.0.0:8000 PonedelkoRazieb.wsgi:application"
    volumes:
      - static_data:/usr/src/static
      - media_data:/usr/src/media
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_data:/usr/src/static/
      - media_data:/usr/src/media/
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf:/etc/letsencrypt/:ro
    depends_on:
      - backend
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    # command: certonly --webroot --webroot-path=/var/www/certbot/ --email bogdanbelenesku@gmail.com --agree-tos --no-eff-email -d my-health.site
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf:/etc/letsencrypt/:rw
    depends_on:
      - nginx

volumes:
  media_data:
  static_data: