# Generated by Django 4.2.7 on 2023-11-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_product_price_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(auto_created=True, null=True, unique=True, verbose_name='Код товара'),
        ),
    ]
